### ISSUE TITLE
sj: execv: No such file or directory

### ISSUE THREAD

**Issue by singpolyma** [younix/sj#8]
When I run:

```
tcpclient xmpp.openmailbox.org 5222 sj -u singpolyma -s openmailbox.org -r sj
```

**Comment by GReagle** [comment]
I am guessing that you are missing tlsc.  Can you confirm?

**Comment by singpolyma** [comment]
@GReagle where do I get tlsc from?

**Comment by singpolyma** [comment]
https://github.com/younix/ucspi lists it... but I did `make && sudo make install` on that

**Comment by GReagle** [comment]
On Tue, Jan 05, 2016 at 12:24:22PM -0800, Stephen Paul Weber wrote:

> https://github.com/younix/ucspi lists it... but I did `make && sudo make install` on that

It doesn't make or install tlsc by default.  You have to do `make
TLS=tlsc tlsc` and `sudo make TLS=tlsc install`.  I have no idea
why it's like that.

**Comment by singpolyma** [comment]
Oh, and that relies on libressl... is there a version of that for Linux yet?

**Comment by younix** [comment]
https://github.com/libressl-portable/portable

**Comment by GReagle** [comment]
Yes, I am running it on Linux.  See https://github.com/libressl-portable/portable.

**Comment by singpolyma** [comment]
Now I'm getting:

```
tlsc: invalid option -- 'u'
```

**Comment by GReagle** [comment]
@singpolyma you are almost there; thank you for your persistence.  This is a known issue in tlsc, see https://github.com/younix/ucspi/issues/5.  Until the bug is fixed, you need to use environment variables.  For example `env SJ_USER=singpolyma SJ_SERVER=openmailbox.org SJ_RESOURCE=sj tcpclient xmpp.openmailbox.org 5222 sj`.  You can also automatically set these environment variables in your shell startup script if you'd like then you don't have to type them again.

**Comment by singpolyma** [comment]
Thanks :)

**Comment by GReagle** [comment]
You're welcome.  Check out sj tools https://github.com/greagle/sjt for some programs to make using sj easier.

**Comment by younix** [comment]
The problem seems to be a gnu-extension in getopt(3). Set the environment variable POSIXLY_CORRECT to force gnu-getopt to behave like POSIX-getopt. This should fix that issue.
